// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaquerSansPere.Backend.WebApi.Data;

#nullable disable

namespace VaquerSansPere.Backend.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320091707_CircleTable")]
    partial class CircleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PVS-BBDD")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Entities.CircleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("Area");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<double>("Perimeter")
                        .HasColumnType("double precision")
                        .HasColumnName("Perimeter");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("Radius");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.HasKey("Id");

                    b.ToTable("circle_data", "PVS-BBDD");
                });

            modelBuilder.Entity("Shared.Models.Entities.ListToOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<int>>("OrderedList")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("OrderedList");

                    b.Property<List<int>>("OriginalList")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("OriginalList");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.HasKey("Id");

                    b.ToTable("order_list_data", "PVS-BBDD");
                });

            modelBuilder.Entity("Shared.Models.Entities.TriangleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Area")
                        .HasColumnType("real")
                        .HasColumnName("Area");

                    b.Property<float>("Base")
                        .HasColumnType("real")
                        .HasColumnName("Base");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("Height");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.HasKey("Id");

                    b.ToTable("triangle_data", "PVS-BBDD");
                });
#pragma warning restore 612, 618
        }
    }
}
